# Generated by Django 4.1.6 on 2023-02-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscribe_delete_follow_subscribe_unique_subscribe'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
